services:
  valkey:
    container_name: "valkey"
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - ./vault/valkey/cache:/data
  pulsar_oxia:
    image: oxia/oxia:latest
    container_name: pulsar_oxia
    hostname: oxia
    restart: on-failure
    networks:
      - pulsar
    volumes:
      - ./vault/pulsar/oxia/oxia-data:/data
    command:
      - oxia
      - standalone
    healthcheck:
      test: ["CMD", "oxia", "health", "--port=6648"]
      interval: 10s
      timeout: 5s
      retries: 30
  
  pulsar:
    image: apachepulsar/pulsar
    container_name: "pulsar"
    networks:
      - pulsar
    environment:
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=128m
    command:
      - bash
      - -c
      - |
        bin/pulsar initialize-cluster-metadata \
        --cluster cluster-a \
        --metadata-store oxia://oxia:6648/default \
        --configuration-store oxia://oxia:6648/default \
        --web-service-url http://broker:8080 \
        --broker-service-url pulsar://broker:6650
    depends_on:
      pulsar_oxia:
        condition: service_healthy
  
  pulsar_bookie:
    image: apachepulsar/pulsar:5.0.0-M1
    container_name: pulsar_broker
    hostname: broker
    restart: on-failure
    networks:
      - pulsar
    environment:
      - PULSAR_MEM=-Xms256m -Xmx256m -XX:MaxDirectMemorySize=128m
    depends_on:
      pulsar_oxia:
        condition: service_healthy
    ports:
      - "6650:6650"
      - "8081:8080"
    command: bash -c "exec bin/pulsar standalone --advertised-address 127.0.0.1"
networks:
   cassandra-net:
      driver: bridge
   pulsar:
      driver: bridge
    